version: '1'
services:
  api:
    container_name: face_api
    image: face_reco_api:v1.0
    working_dir: /face_api
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: always
    runtime: nvidia
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: sh -c "sleep 5s && uvicorn main:app --reload --port 9003 --host 0.0.0.0 --workers 4"
    ports:
      - "9003:9003"
    devices:
      - /dev/nvidia1
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidiactl
    logging:
      options:
        max-size: 50m
    volumes:
      - /home/yeleussinova/data_SSD/face_recognition/face-recognizer-api/face_api/:/face_api


#  triton:
#    image: nvcr.io/nvidia/tritonserver:22.12-py3
#    container_name: tritonserver
#    runtime: nvidia
#    restart: unless-stopped
#    ports:
#      - "8000:8000"
#      - "8001:8001"
#      - "8002:8002"
#    volumes:
#      - "/mnt/sdb1/arman_scripts/face_dataset/triton_api/weights/:/weights"
#    working_dir: /opt/tritonserver/bin
#    shm_size: 1g
#    ulimits:
#      memlock: -1
#      stack: 67108864
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
#    command: ./tritonserver --model-repository=/weights